version: '3.8'

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: garage-db
    environment:
      POSTGRES_DB: garage_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application Spring Boot
  app:
    build: .
    container_name: garage-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/garage_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      PORT: 8080
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data: 