[providers.java]
javaVersion = "21"

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[phases.start]
cmd = "java -jar target/garage-reservation-1.0.0.jar"

[variables]
MAVEN_OPTS = "-Xmx512m" 