[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -jar target/garage-reservation-1.0.0.jar"
healthcheckPath = "/api/creneaux"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 